server:
  port: 8082

spring:
  application:
    name: user-service
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404

  datasource:
    url: jdbc:mysql://localhost:3306/ms_user?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Yg@36368
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Uncomment the following if Keycloak is needed
#app:
#  config:
#    keycloak:
#      server-url: http://localhost:8571
#      realm: banking-service
#      client-id: banking-service-api-client
#      client-secret: 932OFITe8vtH4z0G9gem4Afd69JhbwrI
