spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:mysql://localhost:3306/ms_equence_generator
    username: root
    password: Yg@36368

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083
